name: Build/Test for PR and collaborator push

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - 'docker/**'
      - 'doc/**'
      - 'CHANGELOG.rst'
  push:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - 'docker/**'
      - 'doc/**'
      - 'CHANGELOG.rst'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
        ]
        pkg_mgr : [
          # apt,
          conda,
        ]
        cycamore_tag: [
          latest,
        ]
    
    container:
      image: ghcr.io/cyclus/cycamore_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cycamore:${{matrix.cycamore_tag}}

    steps:
      - name: Checkout Cymetric
        uses: actions/checkout@v3

      - name: Build Cymetric
        run: |
          apt update && apt install -y python3-pip
          python -m pip install --target $(python -m site --user-site) .

      - name: Cymetric Tests
        run: |
          export PYTHONPATH=$(find /root/.local/lib -type d -name 'cyclus-*-*.egg' -print -quit)
          apt update && apt install -y python3-pytest
          cd tests && python -m pytest